
export const APP_ERROR= "APP_ERROR";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const LOGIN_OK= "LOGIN_OK";
export const LOGOUT_OK= "LOGOUT_OK";
export const GET_LOGGED_USER="GET_LOGGED_USER";
export const UNREAD_NOTIFICATION="UNREAD_NOTIFICATION";